AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  EnvironmentStackName:
    Type: String

  LoadBalancerStackName:
    Type: String

Resources:

  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: ENABLED
      PerformanceMode: generalPurpose

  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentStackName}:VpcId
      SecurityGroupIngress:
          - SourceSecurityGroupId:
              Fn::ImportValue: !Sub ${LoadBalancerStackName}:ContainerSG
            IpProtocol: -1

Outputs:
  FileSystemId:
    Description: File system ID
    Value: !Ref FileSystem
    Export:
      Name: !Sub ${AWS::StackName}:FileSystemId